steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/ff-website-ts:$SHORT_SHA',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/ff-website-ts:$SHORT_SHA'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'ff-website-ts',
      '--image', 'gcr.io/$PROJECT_ID/ff-website-ts:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080'
    ]

images:
  - 'gcr.io/$PROJECT_ID/ff-website-ts:$SHORT_SHA'
